### ISSUE TITLE
filtering properties form items in collection

### ISSUE THREAD

**Issue by RaphC** [HubSpot/jackson-jaxrs-propertyfiltering#10]
Hi,

Apparently, the filter doesn't support the filtering of properties from a collection . Do you confirm ?

"items":[
{
"prop1":"myValue1",
"prop2":"myValue2"
},
{
"prop1":"myValue3",
"prop2":"myValue4"
}
]

**Comment by jhaber** [comment]
You should be able to do something like `property=items.prop1` in order to filter out `prop2`. If there's a collection we apply the filtering to every element of the collection. If you're trying to apply different filtering to different collection elements or only return a subset of collection elements, then that isn't currently supported

**Comment by RaphC** [comment]
Sorry, It is possible,

Thanks again for your great work.
